# Generated by Django 5.1.7 on 2025-03-24 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kudosapp", "0002_organization_kudos_user_organization")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kudos_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="kudos_last_reset",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
