# Generated by Django 5.1.7 on 2025-03-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kudosapp", "0003_user_kudos_count_user_kudos_last_reset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="kudos_count",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
