# Generated by Django 5.1.7 on 2025-03-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kudosapp", "0004_alter_user_kudos_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
    ]
