# Generated by Django 5.1.7 on 2025-03-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("kudosapp", "0005_alter_user_first_name_alter_user_last_name")]

    operations = [
        migrations.AddField(
            model_name="kudos",
            name="sender_first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="kudos",
            name="sender_last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
