name: Django CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/kudos/requirements.txt

      - name: Set environment variables from secret
        run: |
          echo "SECRET_KEY=${SECRET_KEY}" >> backend/kudos/.env

      - name: Run migrations
        working-directory: backend/kudos
        run: |
          python manage.py migrate

      - name: Install pre-commit hooks
        run: |
          pre-commit install

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

      - name: Run tests
        working-directory: backend/kudos
        run: |
          pytest
