name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # ─── 1) BACKEND CI ───────────────────────────
  backend-ci:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/kudos/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/kudos/requirements.txt

      - name: Set SECRET_KEY
        run: |
          echo "SECRET_KEY=${SECRET_KEY}" >> backend/kudos/.env

      - name: Migrate database
        working-directory: backend/kudos
        run: python manage.py migrate
      
      - name: Run pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Run tests
        working-directory: backend/kudos
        run: pytest

  # ─── 2) BACKEND CD ───────────────────────────
  backend-deploy:
    needs: backend-ci
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Deploy Backend to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

  # ─── 3) FRONTEND CD ──────────────────────────
  frontend-deploy:
    needs: backend-ci
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build React App
        working-directory: frontend/kudos
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: |
          npm ci
          npm run build

      - name: Deploy Frontend to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_FRONTEND_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
